// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MidStateShuttleService.Models.Data;

#nullable disable

namespace MidStateShuttleService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240311050907_AddCheckInTable")]
    partial class AddCheckInTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusId"));

                    b.Property<string>("BusNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CurrentRouteId")
                        .HasColumnType("int");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("DriverID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("int");

                    b.HasKey("BusId")
                        .HasName("PK__Bus__6A0F60B5718116B1");

                    b.HasIndex("CurrentRouteId");

                    b.HasIndex("DriverId");

                    b.ToTable("Bus");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumb")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DriverId")
                        .HasName("PK__Driver__F1B1CD049A2B343A");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__6A4BEDF69EC0AC18");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasDefaultValue("WI");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("LocationId")
                        .HasName("PK__Location__E7FEA477A8B727BF");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Message", b =>
                {
                    b.Property<int>("ServiceMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceMessageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceMessageId"));

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("DriverID");

                    b.Property<string>("Message1")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("nvarchar(155)")
                        .HasColumnName("Message");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("RouteID");

                    b.HasKey("ServiceMessageId")
                        .HasName("PK__tmp_ms_x__02DEBA9EF8FCEC20");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<bool>("AgreeToTerms")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckedIn")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("FeedBackId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FirstDayExpectingToRide")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PreferContact")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<bool>("SepcialRequest")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SpecialRequestDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TripType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RegistrationId")
                        .HasName("PK__Registra__6EF588103B2104F6");

                    b.HasIndex("FeedBackId");

                    b.HasIndex("RouteId");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.RegistrationDay", b =>
                {
                    b.Property<int>("RegistrationDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RegistrationDayID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationDayId"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int")
                        .HasColumnName("RegistrationID");

                    b.HasKey("RegistrationDayId")
                        .HasName("PK__Registra__F8B74C8E0554913D");

                    b.HasIndex("RegistrationId");

                    b.ToTable("RegistrationDays");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RouteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<string>("AdditionalDetails")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<int>("DropOffLocationId")
                        .HasColumnType("int")
                        .HasColumnName("DropOffLocationID");

                    b.Property<TimeOnly>("DropOffTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("PickUpLocationId")
                        .HasColumnType("int")
                        .HasColumnName("PickUpLocationID");

                    b.Property<TimeOnly>("PickUpTime")
                        .HasColumnType("time");

                    b.HasKey("RouteId")
                        .HasName("PK__Route__80979AAD3C88294B");

                    b.HasIndex("BusId");

                    b.HasIndex("DropOffLocationId");

                    b.HasIndex("PickUpLocationId");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.RouteLocation", b =>
                {
                    b.Property<int>("RouteLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RouteLocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteLocationId"));

                    b.Property<TimeOnly>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsStartLocation")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<int>("NextStopId")
                        .HasColumnType("int")
                        .HasColumnName("NextStopID");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("RouteID");

                    b.HasKey("RouteLocationId")
                        .HasName("PK__RouteLoc__ADC74A46FA981E29");

                    b.HasIndex("LocationId");

                    b.HasIndex("NextStopId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteLocation");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4C2781EAC2");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Bus", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.Data.Route", "CurrentRoute")
                        .WithMany("Buses")
                        .HasForeignKey("CurrentRouteId")
                        .HasConstraintName("FK__Bus__CurrentRout__4E53A1AA");

                    b.HasOne("MidStateShuttleService.Models.Data.Driver", "Driver")
                        .WithMany("Buses")
                        .HasForeignKey("DriverId")
                        .HasConstraintName("FK__Bus__DriverID__4D5F7D71");

                    b.Navigation("CurrentRoute");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Feedback", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.Data.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .HasConstraintName("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Message", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.Data.Driver", "Driver")
                        .WithMany("Messages")
                        .HasForeignKey("DriverId")
                        .IsRequired()
                        .HasConstraintName("FK__Message__DriverI__1DB06A4F");

                    b.HasOne("MidStateShuttleService.Models.Data.Route", "Route")
                        .WithMany("Messages")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("FK__Message__RouteID__1CBC4616");

                    b.Navigation("Driver");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Registration", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.Data.Feedback", "FeedBack")
                        .WithMany("Registrations")
                        .HasForeignKey("FeedBackId")
                        .HasConstraintName("FK__Registrat__FeedB__2739D489");

                    b.HasOne("MidStateShuttleService.Models.Data.Route", "Route")
                        .WithMany("Registrations")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("FK__Registrat__Route__2645B050");

                    b.Navigation("FeedBack");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.RegistrationDay", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.Data.Registration", "Registration")
                        .WithMany("RegistrationDays")
                        .HasForeignKey("RegistrationId")
                        .IsRequired()
                        .HasConstraintName("FK__Registrat__Regis__5AB9788F");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Route", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.Data.Bus", "Bus")
                        .WithMany("Routes")
                        .HasForeignKey("BusId")
                        .IsRequired()
                        .HasConstraintName("FK__Route__BusId__55009F39");

                    b.HasOne("MidStateShuttleService.Models.Data.Location", "DropOffLocation")
                        .WithMany("RouteDropOffLocations")
                        .HasForeignKey("DropOffLocationId")
                        .IsRequired()
                        .HasConstraintName("FK__Route__DropOffLo__19DFD96B");

                    b.HasOne("MidStateShuttleService.Models.Data.Location", "PickUpLocation")
                        .WithMany("RoutePickUpLocations")
                        .HasForeignKey("PickUpLocationId")
                        .IsRequired()
                        .HasConstraintName("FK__Route__PickUpLoc__18EBB532");

                    b.Navigation("Bus");

                    b.Navigation("DropOffLocation");

                    b.Navigation("PickUpLocation");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.RouteLocation", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.Data.Location", "Location")
                        .WithMany("RouteLocationLocations")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK__RouteLoca__Locat__1EA48E88");

                    b.HasOne("MidStateShuttleService.Models.Data.Location", "NextStop")
                        .WithMany("RouteLocationNextStops")
                        .HasForeignKey("NextStopId")
                        .IsRequired()
                        .HasConstraintName("FK__RouteLoca__NextS__1F98B2C1");

                    b.HasOne("MidStateShuttleService.Models.Data.Route", "Route")
                        .WithMany("RouteLocations")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("FK__RouteLoca__Route__57DD0BE4");

                    b.Navigation("Location");

                    b.Navigation("NextStop");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Bus", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Driver", b =>
                {
                    b.Navigation("Buses");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Feedback", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Location", b =>
                {
                    b.Navigation("RouteDropOffLocations");

                    b.Navigation("RouteLocationLocations");

                    b.Navigation("RouteLocationNextStops");

                    b.Navigation("RoutePickUpLocations");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Registration", b =>
                {
                    b.Navigation("RegistrationDays");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.Route", b =>
                {
                    b.Navigation("Buses");

                    b.Navigation("Messages");

                    b.Navigation("Registrations");

                    b.Navigation("RouteLocations");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Data.User", b =>
                {
                    b.Navigation("Feedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
