// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("CheckIn")]
public partial class CheckIn
{
    [Key]
    public int CheckInId { get; set; }

    public int BusId { get; set; }

    public int? RouteId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [StringLength(255)]
    public string Comments { get; set; }

    [DefaultValue(false)]
    public bool FirstTime { get; set; }

    [ForeignKey("RouteId")]
    public virtual Route Route { get; set; }

    [ForeignKey("BusId")]
    public virtual Bus Bus { get; set; }
}