// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("CheckIn")]
public partial class CheckIn
{
    [Key]
    public int CheckInId { get; set; }

    public int? RegisterId { get; set; }

    public int RouteId { get; set; }

    public TimeOnly Date { get; set; }

    [StringLength(255)]
    public string Comments { get; set; }

    public bool FirstTime { get; set; }

    [ForeignKey("RegisterId")]
    [InverseProperty("CheckIns")]
    public virtual Registration Register { get; set; }

    [ForeignKey("RouteId")]
    [InverseProperty("CheckIns")]
    public virtual Route Route { get; set; }
}