// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Driver")]
public partial class Driver
{
    [Key]
    public int DriverId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(20)]
    public string PhoneNumb { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("Driver")]
    public virtual ICollection<Bus> Buses { get; set; } = new List<Bus>();

    [InverseProperty("Driver")]
    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}