// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Feedback")]
[Index("UserId", Name = "IX_Feedback_UserID")]
public partial class Feedback
{
    [Key]
    [Column("FeedbackID")]
    public int FeedbackId { get; set; }

    [Required]
    [StringLength(255)]
    public string Comment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateSubmitted { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    [InverseProperty("FeedBack")]
    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();

    [ForeignKey("UserId")]
    [InverseProperty("Feedbacks")]
    public virtual User User { get; set; }
}