// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Message")]
[Index("DriverId", Name = "IX_Message_DriverID")]
[Index("RouteId", Name = "IX_Message_RouteID")]
public partial class Message
{
    [Key]
    public int MessageId { get; set; }

    [Required(ErrorMessage = "A message is required.")]
    [StringLength(160, ErrorMessage = "This field must not be more than 50 characters.")]
    [RegularExpression("^[A-Za-z\\s]{2,}$", ErrorMessage = "Must contain only characters and be at least 2 characters long")]
    public string Name { get; set; }

    [Required(ErrorMessage = "A message is required.")]
    [StringLength(160, ErrorMessage = "This field must not be more than 160 characters.")]
    public string MessageContent { get; set; }

    [DefaultValue(false)]
    public bool ResponseRequired { get; set; }

    [StringLength(50)]
    public string? ContactInfo { get; set; }
}