// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Registration")]
[Index("FeedBackId", Name = "IX_Registration_FeedBackId")]
[Index("RouteId", Name = "IX_Registration_RouteId")]
public partial class Registration
{
    [Key]
    public int RegistrationId { get; set; }

    public int RouteId { get; set; }

    [StringLength(450)]
    public string UserId { get; set; }

    [Required]
    [StringLength(20)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(20)]
    public string LastName { get; set; }

    [Required]
    [StringLength(10)]
    public string Phone { get; set; }

    [Required]
    [StringLength(20)]
    public string PreferContact { get; set; }

    [Required]
    [StringLength(40)]
    public string Email { get; set; }

    public bool AgreeToTerms { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SpecialRequestDate { get; set; }

    public bool SepcialRequest { get; set; }

    public int? FeedBackId { get; set; }

    [StringLength(10)]
    public string TripType { get; set; }

    public DateOnly? FirstDayExpectingToRide { get; set; }

    [InverseProperty("Register")]
    public virtual ICollection<CheckIn> CheckIns { get; set; } = new List<CheckIn>();

    [ForeignKey("FeedBackId")]
    [InverseProperty("Registrations")]
    public virtual Feedback FeedBack { get; set; }

    [InverseProperty("Registration")]
    public virtual ICollection<RegistrationDay> RegistrationDays { get; set; } = new List<RegistrationDay>();

    [ForeignKey("RouteId")]
    [InverseProperty("Registrations")]
    public virtual Route Route { get; set; }
}