// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Index("RegistrationId", Name = "IX_RegistrationDays_RegistrationID")]
public partial class RegistrationDay
{
    [Key]
    [Column("RegistrationDayID")]
    public int RegistrationDayId { get; set; }

    [Column("RegistrationID")]
    public int RegistrationId { get; set; }

    [Required]
    [StringLength(10)]
    public string DayOfWeek { get; set; }

    [ForeignKey("RegistrationId")]
    [InverseProperty("RegistrationDays")]
    public virtual Registration Registration { get; set; }
}