// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Route")]
[Index("BusId", Name = "IX_Route_BusId")]
[Index("DropOffLocationId", Name = "IX_Route_DropOffLocationID")]
[Index("PickUpLocationId", Name = "IX_Route_PickUpLocationID")]
public partial class Route
{
    [Key]
    public int RouteId { get; set; }

    public int PickUpLocationId { get; set; }

    public int DropOffLocationId { get; set; }

    public TimeOnly PickUpTime { get; set; }

    public TimeOnly DropOffTime { get; set; }

    [StringLength(300)]
    public string AdditionalDetails { get; set; }

    [DefaultValue(false)]
    public bool IsArchived { get; set; }

    public int BusId { get; set; }

    // Navigation property representing the associated bus
    // Lets entity know CurrentRouteId is a FK to the route table
    [ForeignKey("BusId")]
    public virtual Bus Bus { get; set; }

    // Navigation property representing the current route location associated with this route.
    // Lets entity know PickUpLocationID is a FK to the RouteLocation table
    [ForeignKey("PickUpLocationID")]
    public virtual RouteLocation PickUpLocation { get; set; }

    // Navigation property representing the current route location associated with this route.
    // Lets entity know DropOffLocationId is a FK to the RouteLocation table
    [ForeignKey("DropOffLocationId")]
    public virtual RouteLocation DropOffLocation { get; set; }
}