// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Bus")]
public partial class Bus
{
    [Key]
    public int BusId { get; set; }

    public int? BusNo { get; set; }

    public int? PassengerCapacity { get; set; }

    public int? DriverId { get; set; }

    public bool? IsActive { get; set; }

    public virtual Driver Driver { get; set; }
}