// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Bus")]
[Index("CurrentRouteId", Name = "IX_Bus_CurrentRouteId")]
[Index("DriverId", Name = "IX_Bus_DriverID")]
public partial class Bus
{
    [Key]
    public int BusId { get; set; }

    [Required]
    [StringLength(50)]
    public string BusNo { get; set; }

    public int PassengerCapacity { get; set; }

    [Column("DriverID")]
    public int? DriverId { get; set; }

    public bool IsActive { get; set; }

    public int? CurrentRouteId { get; set; }

    [ForeignKey("CurrentRouteId")]
    [InverseProperty("Buses")]
    public virtual Route CurrentRoute { get; set; }

    [ForeignKey("DriverId")]
    [InverseProperty("Buses")]
    public virtual Driver Driver { get; set; }

    [InverseProperty("Bus")]
    public virtual ICollection<Route> Routes { get; set; } = new List<Route>();
}