// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Bus")]
public partial class Bus
{
    [Key]
    public int BusId { get; set; }

    [StringLength(50)]
    public string BusNo { get; set; }

    public int PassengerCapacity { get; set; }

    [ForeignKey("Driver")]
    public int? DriverId { get; set; }

    [DefaultValue(false)]
    public bool IsActive { get; set; }

    public int? CurrentRouteId { get; set; } // Foreign key for the current route

    // Navigation property representing the current route associated with this bus.
    // Lets entity know CurrentRouteId is a FK to the route table(Because the FK and PK are named different this is needed).
    [ForeignKey("CurrentRouteId")]
    public virtual Routes CurrentRoute { get; set; }
}