// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("CheckIn")]
public partial class CheckIn
{
    [Key]
    public int CheckInId { get; set; }

    public int BusId { get; set; }

    public int BusNumber { get; set; }

    public int? RouteId { get; set; }

    public string? Name { get; set; }

    public DateTime Date { get; set; }

    [StringLength(255)]
    public string Comments { get; set; }

    public bool FirstTime { get; set; }

    public int LocationId { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("RouteId")]
    public virtual Routes Route { get; set; }

    [ForeignKey("BusId")]
    public virtual Bus Bus { get; set; }

    [ForeignKey("LocationId")]
    public virtual Location Location { get; set; }
}