// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Driver")]
public partial class Driver
{
    [Key]
    public int DriverId { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(20)]
    public string PhoneNumber { get; set; }

    public bool IsActive { get; set; }
}