// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Feedback")]
public partial class Feedback
{
    [Key]
    public int FeedbackId { get; set; }

    [StringLength(255, ErrorMessage = "Comment should not exceed 255 characters.")]
    public string Comment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateSubmitted { get; set; }

    [StringLength(50)] // Set the maximum length to 50
    public string CustomerName { get; set; } // Changed from UserId

    [Required(ErrorMessage = "Rating is required.")]
    [Range(1, 5, ErrorMessage = "Rating must be between 1 and 5.")]
    public int Rating { get; set; } // Added Rating property

    [Required]
    [Column("DisplayTestimonial")]
    public bool DisplayTestimonial { get; set; } // Added DisplayTestimonial property

    public bool IsActive { get; set; }
}