// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Feedback")]
[Index("UserId", Name = "IX_Feedback_UserID")]
public partial class Feedback
{
    [Key]
    public int FeedbackId { get; set; }

    [StringLength(255)]
    public string Comment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateSubmitted { get; set; }

    [ForeignKey("User")]
    public int? UserId { get; set; }

    // One to one relationship with User
    [InverseProperty("Feedbacks")]
    public virtual User User { get; set; }
}