// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Feedback")]
public partial class Feedback
{
    [Key]
    public int FeedbackId { get; set; }

    [StringLength(255)]
    public string Comment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateSubmitted { get; set; }

    [StringLength(50)] // Set the maximum length to 50
    public string CustomerName { get; set; } // Changed from UserId

    public int Rating { get; set; } // Added Rating property
}