// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Message")]
[Index("DriverId", Name = "IX_Message_DriverID")]
[Index("RouteId", Name = "IX_Message_RouteID")]
public partial class Message
{
    [Key]
    [Column("ServiceMessageID")]
    public int ServiceMessageId { get; set; }

    [Column("RouteID")]
    public int RouteId { get; set; }

    [Column("DriverID")]
    public int DriverId { get; set; }

    [Required]
    [Column("Message")]
    [StringLength(155)]
    public string Message1 { get; set; }

    [ForeignKey("DriverId")]
    [InverseProperty("Messages")]
    public virtual Driver Driver { get; set; }

    [ForeignKey("RouteId")]
    [InverseProperty("Messages")]
    public virtual Route Route { get; set; }
}