// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("RouteLocation")]
[Index("LocationId", Name = "IX_RouteLocation_LocationID")]
[Index("NextStopId", Name = "IX_RouteLocation_NextStopID")]
[Index("RouteId", Name = "IX_RouteLocation_RouteID")]
public partial class RouteLocation
{
    [Key]
    public int RouteLocationId { get; set; }

    public int RouteId { get; set; }

    public int LocationId { get; set; }

    public int NextStopId { get; set; }

    [Column(TypeName = "time")]
    public TimeSpan ArrivalTime { get; set; }

    [Column(TypeName = "time")]
    public TimeSpan DepartureTime { get; set; }

    [DefaultValue(false)]
    public bool IsStartLocation { get; set; }

    [ForeignKey("LocationId")]
    [InverseProperty("RouteLocationLocations")]
    public virtual Location Location { get; set; }

    [ForeignKey("NextStopId")]
    [InverseProperty("RouteLocationNextStops")]
    public virtual Location NextStop { get; set; }

    [ForeignKey("RouteId")]
    [InverseProperty("RouteLocations")]
    public virtual Route Route { get; set; }
}