// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("Route")]
[Index("BusId", Name = "IX_Route_BusId")]
[Index("DropOffLocationId", Name = "IX_Route_DropOffLocationID")]
[Index("PickUpLocationId", Name = "IX_Route_PickUpLocationID")]
public partial class Route
{
    [Key]
    [Column("RouteID")]
    public int RouteId { get; set; }

    [Column("PickUpLocationID")]
    public int PickUpLocationId { get; set; }

    [Column("DropOffLocationID")]
    public int DropOffLocationId { get; set; }

    public TimeOnly PickUpTime { get; set; }

    public TimeOnly DropOffTime { get; set; }

    [StringLength(300)]
    public string AdditionalDetails { get; set; }

    public bool IsArchived { get; set; }

    public int BusId { get; set; }

    [ForeignKey("BusId")]
    [InverseProperty("Routes")]
    public virtual Bus Bus { get; set; }

    [InverseProperty("CurrentRoute")]
    public virtual ICollection<Bus> Buses { get; set; } = new List<Bus>();

    [InverseProperty("Route")]
    public virtual ICollection<CheckIn> CheckIns { get; set; } = new List<CheckIn>();

    [ForeignKey("DropOffLocationId")]
    [InverseProperty("RouteDropOffLocations")]
    public virtual Location DropOffLocation { get; set; }

    [InverseProperty("Route")]
    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    [ForeignKey("PickUpLocationId")]
    [InverseProperty("RoutePickUpLocations")]
    public virtual Location PickUpLocation { get; set; }

    [InverseProperty("Route")]
    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();

    [InverseProperty("Route")]
    public virtual ICollection<RouteLocation> RouteLocations { get; set; } = new List<RouteLocation>();
}